# version: "3.9"
services:
  mongodb:
    image: mongo:7.0.1
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-thisisasecret123}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-dnd}
    restart: unless-stopped

  # mariadb:
  #   image: mariadb:10.11.5
  #   # image: mariadb:latest
  #   volumes:
  #     - ../data/mariadb:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: thisisasecret123
  #     MYSQL_DATABASE: dnd
  #   ports:
  #     - "3306:3306"
  #   restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped

  workers:
    image: dn-dashboard-workers:latest
    build:
      context: ../
      dockerfile: workers/Dockerfile
    environment:
      MONGO_HOST: ${MONGO_HOST:-mongodb}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE:-dnd}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  backend:
    image: dn-dashboard-backend:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "4000:3002" # Map NestJS app to localhost:4000
    environment:
      NODE_ENV: production
      MONGO_HOST: ${MONGO_HOST:-mongodb}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE:-dnd}
    restart: unless-stopped
    volumes:
      - ../backend:/app # Optional: Mount the backend code for local development
    depends_on:
      - mongodb

  frontend:
    image: dn-dashboard-frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000" # Map Nuxt.js app to localhost:3000
    environment:
      NODE_ENV: production
      # GRAPHQL_BACKEND_URL: http://192.168.1.209:4000
      GRAPHQL_BACKEND_URL: ${GRAPHQL_BACKEND_URL}
    restart: unless-stopped
    # volumes:
    #   - ../frontend:/app # Optional: Mount the frontend code for local development
    depends_on:
      - backend
