# version: "3.9"
services:
  dnd-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000" # Map Nuxt.js app to localhost:3000
    environment:
      NODE_ENV: production
    volumes:
      - ../frontend:/app # Optional: Mount the frontend code for local development
    depends_on:
      - dnd-backend

  dnd-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "4000:3002" # Map NestJS app to localhost:4000
    environment:
      NODE_ENV: production
    volumes:
      - ../backend:/app # Optional: Mount the backend code for local development
    # depends_on:
    #   - db

  # db:
  #   image: postgres:15
  #   container_name: postgres
  #   ports:
  #     - "5432:5432" # Map PostgreSQL database to localhost:5432
  #   environment:
  #     POSTGRES_USER: yourusername
  #     POSTGRES_PASSWORD: yourpassword
  #     POSTGRES_DB: yourdatabase
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
# networks:
#   default:
#     external:
#       name: dn-network
