# version: "3.9"
services:
  mongodb:
    image: mongo:7.0.1
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-thisisasecret123}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-dnd}
      MONGO_HOST: ${MONGO_HOST:-mongodb}
      MONGO_PORT: ${MONGO_PORT:-27017}
    restart: unless-stopped
    volumes:
      - ../data/mongodb:/data/db

  # mariadb:
  #   image: mariadb:10.11.5
  #   # image: mariadb:latest
  #   volumes:
  #     - ../data/mariadb:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: thisisasecret123
  #     MYSQL_DATABASE: dnd
  #   ports:
  #     - "3306:3306"
  #   restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped

  workers:
    image: dn-dashboard-workers:latest
    build:
      context: ../
      dockerfile: workers/Dockerfile
      args:
        - BULLMQ_PORT=3000 # default port for bullmq, this is internal port
    ports:
      - "${BULLMQ_PORT:-3001}:3000" # external to internal port mapping
    environment:
      # MONGO_HOST: ${MONGO_HOST:-mongodb}
      # MONGO_PORT: ${MONGO_PORT:-27017}
      # MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      # MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # MONGO_DATABASE: ${MONGO_INITDB_DATABASE:-dnd}
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      RPC_URL_POLKADOT: ${RPC_URL_POLKADOT:-wss://rpc.metaspan.io/polkadot}
      RPC_URL_KUSAMA: ${RPC_URL_KUSAMA:-wss://rpc.metaspan.io/kusama}
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  backend:
    image: dn-dashboard-backend:latest
    build:
      context: ../
      dockerfile: backend/Dockerfile
      args:
        - PORT=3000 # default port for backend
    ports:
      - "${GRAPHQL_PORT:-3002}:3000" # Map NestJS app to localhost:3000
    environment:
      NODE_ENV: production
      MONGO_HOST: ${MONGO_HOST:-mongodb}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE:-dnd}
    restart: unless-stopped
    # volumes:
      # - ../backend:/app # Optional: Mount the backend code for local development
    depends_on:
      - mongodb

  frontend:
    image: dn-dashboard-frontend:latest
    build:
      context: ../
      dockerfile: frontend/Dockerfile
      args:
        - PORT=3000 # default port for frontend
        - GRAPHQL_API_URL=${GRAPHQL_API_URL}
    ports:
      - "${FRONTEND_PORT:-3003}:3000" # Map Nuxt.js app to localhost:3000
    environment:
      NODE_ENV: production
      # GRAPHQL_BACKEND_URL: http://192.168.1.209:4000
      GRAPHQL_API_URL: ${GRAPHQL_API_URL}
    restart: unless-stopped
    # volumes:
    #   - ../frontend:/app # Optional: Mount the frontend code for local development
    depends_on:
      - backend
